### ISSUE TITLE
is this useable? serialize() type definition says it returns null

### ISSUE THREAD

**Issue by akleiber** [andersondanilo/jsonapi-fractal#1]
Hi @andersondanilo 

Thank you for starting this! 
It is listed at https://jsonapi.org/implementations/#server-libraries-node-js but as the type definition of `serialize` say it returns `null` I wonder if this is in any shape to be used?

![Bildschirmfoto 2020-04-29 um 22 30 21](https://user-images.githubusercontent.com/1506973/80643868-119e2f00-8a69-11ea-9092-3e78867cf9cd.png)

**Comment by andersondanilo** [comment]
I fixed the type definition (i was not defining a type for the return)

I am using this project in one Javascript project and recently another TypeScript project. Until the moment i have no problems.
