### ISSUE TITLE
Update Library

### ISSUE THREAD

**Issue by johannesschobel** [andersondanilo/jsonapi-fractal#10]
Dear @andersondanilo ,
this library seems really easy to use. However, i noticed, that there are several features from json:api missing - for example, errors. Or features are broken, like the `options.fields` attribute, ...

Are you planning to maintain this library?
All the best,
Johannes

**Comment by andersondanilo** [comment]
Hello Johan,
The project is open to PR's, lately i don't have much time, but will try to review as soon as possible

**Comment by johannesschobel** [comment]
Dear @andersondanilo ,
thanks for the infos. i will try to contribute, if i find time. currently, i am very busy at work, but we will see 😆
