### ISSUE TITLE
Arguments of serialize function

### ISSUE THREAD

**Issue by nikdimtenko** [andersondanilo/jsonapi-fractal#8]
https://github.com/andersondanilo/jsonapi-fractal/blob/580b7fbf6c940b1fd437d51b18120afabe9b1533/src/serializer.ts#L13
Third argument of serialize **options** can be optional. This is more comfortable when we use TS, because we do not write an empty object as third argument.

**Comment by andersondanilo** [comment]
fixed! in the last version this is optional
